### ISSUE TITLE
Windows Secuirty pop-up usually isn't focused when prompted for login

### ISSUE THREAD

**Issue by GoldenHashtag** [Angelelz/WinHelloUnlock#11]
**Describe the bug**
Windows Security pop-up usually loses focus when prompted.

**To Reproduce**
Open any database with windows hello setup, you'll notice that Windows Security is behind of KeePass.

**Expected behavior**
Windows Security pop-up should be on top.

**Screenshots**
![image](https://user-images.githubusercontent.com/40300931/63213790-19b87780-c143-11e9-85dd-f40a9d95a242.png)

**Additional context**
There's a bug (or not) in Windows where you fail the Windows Hello Face (Not PIN) when Windows Security pop-up isn't focused. Combining with this issue makes unlocking rather frustrating as you fail over and over and over again. Maybe it's a Windows issue but simpler solution would be fixing the non-focus issue on your end.
![image](https://user-images.githubusercontent.com/40300931/63213750-add60f00-c142-11e9-90b1-b25822edb696.png)

**Comment by Angelelz** [comment]
I didn't want to do it like this, the hard way! forcing Security Prompt to the foreground even if user tries to click somewhere else. Please download v1 just released.
