### ISSUE TITLE
Windows Hello prompt won't appear in specific condition

### ISSUE THREAD

**Issue by GoldenHashtag** [Angelelz/WinHelloUnlock#13]
**Describe the bug**
Windows Hello prompt won't appear.

**To Reproduce**
1)Make sure KeePass is closed;
2)Open the database with Windows Hello setup;
3)Click Cancel, a warning "The request was cancelled by the user" should appear;
4)Click OK, the standard unlock prompt should appear;
5)Click Cancel, then open the database with the same window (File - Open Recent);
6)You'll see that Windows Hello prompt won't appear, instead the standard prompt appears;
7)Then click Cancel, and open database again (File - Open Recent);
8)You'll see nothing appears.

**Expected behavior**
1) Windows Hello prompt should appear before standard prompt in 6);
2) Windows Hello prompt should appear in 8), and should ask for standard prompt when refused to use Windows Hello.

**Comment by Angelelz** [comment]
Step 6 is actual expected behavior. For security you have only one chance to unlock with Windows Hello. If unsuccessful fall back to regular unlock prompt. You can try again with Windows Hello if you close KeePass entirely and open again.

Step 8 is not expected behavior. Should be worked on!

**Comment by GoldenHashtag** [comment]
> Step 6 is actual expected behavior. For security you have only one chance to unlock with Windows Hello. If unsuccessful fall back to regular unlock prompt. You can try again with Windows Hello if you close KeePass entirely and open again.
> Step 8 is not expected behavior. Should be worked on!

i see but, that seems inconsistent because Windows Hello handles "when pin wrong".

![image](https://user-images.githubusercontent.com/40300931/63232282-fa137300-c258-11e9-8325-8003d3162fbf.png)
(This is from another plugin but they are they same, as Windows Hello won't notify applications that you typed the wrong pin)
that means your plugin never know if the first verification is failed, instead Windows Hello will lock itself when failed for many times (but your plugin still won't know it).
secondly you can still try Windows Hello unlock after restarting KeePass, which makes "you have only one chance to unlock with Windows Hello." pointless because you still have the ability to try with Windows Hello after first fail.

**Comment by Angelelz** [comment]
Yes, Windows Hello APIs are very limited and kind of obscure, but if the user cancels or Windows Hello auth is unsuccessful, the plugin should not try to use it again. If the user wants to try again, he/she has the ability to restart keepass to do so.
