### ISSUE TITLE
Plugin not compatible with KeeAnywhere

### ISSUE THREAD

**Issue by GoldenHashtag** [Angelelz/WinHelloUnlock#14]
**Describe the bug**
This plugin won't work when KeeAnywhere is installed.
(https://chocolatey.org/packages/keepass-plugin-keeanywhere)
(https://github.com/Kyrodan/KeeAnywhere)

**To Reproduce**
1)Install KeeAnywhere;
2)Open database from cloud drive;
3)You'll see this plugin stops working.

**Expected behavior**
This plugin should work with KeeAnywhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/40300931/63220242-eb27b480-c1b5-11e9-8fca-9c2ad1bbb986.png)

**Additional context**
KeeAnywhere reads database from cloud drive, the way WinHelloUnlock handles composite key is by remembering the database location, and it doesn't work well with KeeAnywhere since the database isn't at a local drive.

Log file: https://pastebin.com/crFDJyVY

**Comment by Angelelz** [comment]
I'm not sure this issue is in the scope of this plugin, It is not stated anywhere but this plugin is for local databases. But this exception should definitely be handled!
That being said, It should not be too hard to add the support you are asking. Gotta work first on #12 and #13 though.
