### ISSUE TITLE
WinHelloUnlock can't be re-added ones removed from DB

### ISSUE THREAD

**Issue by sambul13** [Angelelz/WinHelloUnlock#19]
WinHelloUnlock can't be re-added ones you remove it from DB Options. Its Tab disappears from Options, and its impossible to re-add the plugin to the same database ever again. Plugin reinstall doesn't fix the issue. No prompts to setup the plugin again, or reselect it in options, or enter fingerprint again.

**To Reproduce**
1. Go to 'Tools-Options-WinHelloUnlock'
2. Deselect "Enable WinHelloUnlock for this DB" - OK to close Options
3. Exit and launch KeePass 2.42.1 again
4. There is no prompt to setup the plugin again after KeePass start
5. Go to 'Tools-Options'. There is no Tab anymore "WinHelloUnlock", so you can't re-enable the plugin.

Expected Behavior
WinHelloPlugin Tab remains visible after "Enable WinHelloUnlock for this DB" is deselected in Options, including when KeePass is exited and re-launched.

**Comment by Angelelz** [comment]
Yes, I am able to reproduce. While I work on the issue, you can re-enable the plugin for your database by deleting the WinHelloUnlock custom data:
1. Go to Tool > Database Tools > Database Maintenance...
2. Click on "Plugin Data" tab
3. Select the one named "WinHelloUnlock" and click delete
4. Save the database and you will be asked is you want to set WinHelloUnlock for the database.
