### ISSUE TITLE
Cancelling Fingerprint Prompt causes errors

### ISSUE THREAD

**Issue by sambul13** [Angelelz/WinHelloUnlock#24]
**Describe the bug**
WinHelloUnlock Prompt shows errors when cancelled by Esc button.

**To Reproduce**

1. Open KeePass. See WinHelloUnlock Fingerprint prompt appears.
2. Press Esc to cancel WinHelloUnlock fingerprint entry and instead access default Password Entry prompt.
3. WinHelloUnlock prompt doesn't close right away, thus exposing default Password Prompt, but gives a sequence of errors.

**Expected behavior**
On pressing Esc, WiinHelloUnlock prompt closes without any errors or questions, while exposing default Password Prompt

**Comment by Angelelz** [comment]
Thanks for reporting, I can reproduce.
