### ISSUE TITLE
WinHelloUnlock stops working when update is available

### ISSUE THREAD

**Issue by sambul13** [Angelelz/WinHelloUnlock#25]
**Describe the bug**
When KeePass shows a plugin & package Update Prompt at launch, and user closes it, WinHelloUnlock doesn't show Scan Prompt after that and fails to work

**To Reproduce**
1. Open KeePass
2. KeePass Prompt appears "Updates available" if there are any
3. You can't close the prompt and scan your finger anymore until the update is installed, and KeePass restarted, if KeePass update notifications remain On

**Expected behavior**
WinHelloUnlock should show Scan Prompt and allow user to scan fingerprint and enter KeePass once KeePass Update Prompt is closed by the user.

**Comment by Angelelz** [comment]
Yes, I am aware of the issue, it was introduced when closing #12.
After attempting to open the database, the plugin checks if the file was actually opened, If it was not, then the master key might have changed (Hence, the prompt from the plugin). If KeePass is checking for updates and finds any, it doesn't open the database right away but shows the obsolete components, that's why it fails.
I am testing another way of closing #12 that doesn't cause this issue.

**Comment by Angelelz** [comment]
It would be very helpful if you could test this
[WinHelloUnlock.zip](https://github.com/Angelelz/WinHelloUnlock/files/3538341/WinHelloUnlock.zip) build from [EscButtonBugFix](https://github.com/Angelelz/WinHelloUnlock/tree/EscButtonBugFix) branch with my attempt to fix this issue.
I am testing but even though I downgraded some plugins, I can't get KeePass to check for update when I'm trying to unlock a database.

**Comment by sambul13** [comment]
Just tested. Still shows KeePass warning prompt at pressing Esc "Error decrypoting the data. The request was cancelled by the user".

It sounds like you submit the request to decrypt data before finger scan is done.

**Comment by Angelelz** [comment]
> Just tested. Still shows KeePass warning prompt at pressing Esc "Error decrypting the data. The request was cancelled by the user". Pressing OK in that prompt shows "Enter Password" prompt.

That is actually expected behaviour! Esc key should be equivalent to clicking cancel button!
> Mark KeePass - Options - Advanced - Check for updates at KeePass startup. Then downgrade your plugin version, and re-launch KeePass.

I did that but for some reason it doesn't work.

Anyway, I am asking about the issue in this thread. Is WinHelloUnlock working when it checks for updates?
