### ISSUE TITLE
Whenever it is saved, it asks whether to update WinHelloUnlock.

### ISSUE THREAD

**Issue by zzala0** [Angelelz/WinHelloUnlock#28]
Thanks for this feature.
Whenever it is saved, it asks whether to update WinHelloUnlock.
Can I skip this step for a database that is already allowed?

**Comment by Angelelz** [comment]
Can you please specify better? With steps to reproduce? I'm not seeing this issue. It only ask you to update if you change your master password, or that is the intention.

**Comment by zzala0** [comment]
The master key has not been changed.
When I modify and save the contents of the database, it asks if I want to update each time.
I guess it's a matter of using fingerprints on two different computers and synchronizing their databases.

**Comment by Angelelz** [comment]
That could be the issue, but it shouldn't! Because the master key information is saved locally in a credential.
I don't have at hand another PC with Windows Hello to test this, but I can borrow a friend's laptop and will come back here. Thanks for the issue report!

**Comment by zzala0** [comment]
> Question: When you sync the database, is it able to unlock it when coming from the other PC?

I did not use 2 PC at the same time.

**Comment by Angelelz** [comment]
> I guess it's a matter of using fingerprints on two different computers and synchronizing their databases.

Please, provide more information: What other plugins do you use? What do you use to sync the databases? Does it happen only when you sync or all the time you change something? I need to be able to reproduce to fix. Please provide steps to reproduce!

**Comment by zzala0** [comment]
> > I guess it's a matter of using fingerprints on two different computers and synchronizing their databases.
> 
> Please, provide more information: What other plugins do you use? What do you use to sync the databases? Does it happen only when you sync or all the time you change something? I need to be able to reproduce to fix. Please provide steps to reproduce!

I am using the portable version.
Maybe the program settings are the problem.
Attached
the db with the program I am using.
password is "issue0911!"
[KeePass.zip](https://github.com/Angelelz/WinHelloUnlock/files/3596530/KeePass.zip)

**Comment by Angelelz** [comment]
Wow, this was a weird issue to fix. But there it is the new [v1.3.2 version](https://github.com/Angelelz/WinHelloUnlock/releases/tag/v1.3.2)! Thanks for reporting and answering fast!

**Comment by Angelelz** [comment]
Can you confirm it is fixed? Because I'm still checking and seeing mixed results... What a weird thing!

**Comment by zzala0** [comment]
> Can you confirm it is fixed? Because I'm still checking and seeing mixed results... What a weird thing!

The problem is solved. Thanks for the quick fix.
I like this feature so much. :)
