### ISSUE TITLE
Autofill unlocks, but does not fill

### ISSUE THREAD

**Issue by BananaAcid** [Angelelz/WinHelloUnlock#31]
CTRL + ALT + A (and CTRL+ALT+SHIFT+A) ... just unlocks.

- it does not autofill
- it does not cloase the DB again (if it was locked)

What it should do:
- unlock
- trigger the default autofill
- lock again.

**Comment by Angelelz** [comment]
Ok, let me look into it. I've encounter this myself when autotyping. I just press the shortcut again, but It's kinda inconvenient.

**Comment by Angelelz** [comment]
I have a working fix in another branch, but I'm not sure we should lock the DB again after Autotype is performed. I've tested other QuickUnlock plugins but neither does it, not even regular unlock. I mean, if you autotype without any plugin while keepass is locked, keepass will remain unlocked after autotype is finished. So I think,

What it should do:

- unlock
- trigger the default autofill

Do you think locking again could be a good feature? I am not sure

**Comment by BananaAcid** [comment]
It should. Yes others are lacking this feature too. It is about security.
If you autofill, grab a cup of coffee, the DB is still unlocked while being away ... even thought unlocking was only meant for a single action: autofill.
Every autofill requires a manual locking again.

Just add a checkbox to the options ;)

**Comment by Angelelz** [comment]
Thanks for reporting. It is a nice feature to have in options. You can download latest version.

**Comment by Angelelz** [comment]
I can't reproduce what you are describing! Only `Enable WinHelloUnlock for this database` checkbox disables all the buttons.
