### ISSUE TITLE
Login window not visible when database without Hello-Access is detected

### ISSUE THREAD

**Issue by naobug** [Angelelz/WinHelloUnlock#33]
**Describe the bug**
When there is no Windows Hello access set up for the current database then the login window of KeePass2 is not visible.

**To Reproduce**
1. Database exists and is set up, but does not have WinHelloUnlock configured.
2. place the plugin dll in the directory
3. startup KeePass
4. Login window for Keepass is only visible in the Windows Taskbar but not on the screen (as if the pop would be minimized). Hovering the mouse cursor shows the thumbnail of the login window including the animated blinking cursor. You can type your password and hit enter and it will login but you don't see this on the screen. Also in the taskswitcher Keepass is shown twice.

**Expected behavior**
The login window should be visible.

**Additional context**
Windows 10 1903 - 18362.418
Windows color settings: transparency enabled, accent colors enabled (see screenshot) {don't know if relevant}
Nvidia Graphics Card (1070ti)
Keepass Version 2.43

Loaded Plugin:
CertKeyProviderPlugin 2.0.8.3
KeePassHttp 1.8.4.2
KeePassRPC 1.9.0.0
WinHelloUnlock 1.4
![windows color settings](https://user-images.githubusercontent.com/12033198/67390345-caf0e900-f59c-11e9-8629-7d0035dd6486.jpg)
![taskswitcher](https://user-images.githubusercontent.com/12033198/67390350-ce847000-f59c-11e9-9de6-e8b685c65937.jpg)

**Comment by Angelelz** [comment]
Thanks for reporting! This is a case I didn't test for. Should be an easy fix.

**Comment by Angelelz** [comment]
New release ready, sorry for the inconvenience!
