### ISSUE TITLE
[Feature Request] If windows hello is not available, avoid popups 

### ISSUE THREAD

**Issue by moryoav** [Angelelz/WinHelloUnlock#35]
I run keepass on 2 computers, one with hello face unlock and one without it. On the one with Hello face unlock, I received a message asking me if I want to set up the Hello face unlock, I did, everything worked fine. On the other computer, I don't have a camera at all, I open Keepass, I get a popup msgbox with the question if I want to set up face unlock, If I say yes, it tells me that Hello isn't available on this computer. If you'd just reverse the order in the logics here, and first check if Hello is even available, then we could avoid these annoying popups every time keepass is opened.

**Comment by Angelelz** [comment]
I understand the issue, but before I do anything, Would you try to uninstall WinHelloUnlock in the computer where you don't have Windows Hello available? If you don't have the plugin in the PC where you don't have Windows Hello, It won't bother you with any pop up. Sorry for the late answer, I've been busier lately.

**Comment by moryoav** [comment]
I'm using keepass portable that's saved on a flash drive. I can't remove a plugin on a per computer basis, it's either installed or it's not...

**Comment by Angelelz** [comment]
Ok, that is a an use case I didn't consider. I will change the logic accordingly as soon as I can. Thanks for reporting!

**Comment by Angelelz** [comment]
It was a small fix, I don't feel it should make a new release. If you want to use it before the new release is published use [this one](https://github.com/Angelelz/WinHelloUnlock/files/3839469/WinHelloUnlock.zip) (unzip it first) from [another branch](https://github.com/Angelelz/WinHelloUnlock/tree/WinHelloAvailabilityCheck), and please tell me if that solves your issue.

**Comment by moryoav** [comment]
Perfect, works great. Thank you!
