### ISSUE TITLE
error setting hello for new db

### ISSUE THREAD

**Issue by BananaAcid** [Angelelz/WinHelloUnlock#36]
**Describe the bug**
after doing the initial finger scan, an error window pops up:
"Error saving the composite key: The System can not find the designated file. Safe could not be opened"
actually it is in german:
"Error saving the composite key: Das System kann die angegebene Datei nicht finden. Tresor kann nicht geöffnet werden."

![Unbenannt](https://user-images.githubusercontent.com/1894723/68982254-8f95b300-0806-11ea-9927-125643086056.PNG)

**Comment by Angelelz** [comment]
I might need a little more information:
Windows Version?
Database location (local o network)?
MasterKey components (password + keyfile + Windows user)?

I implemented that error, but I've never seen it showing up.

**Comment by BananaAcid** [comment]
Windows Version: 10 (no idea what it is of today)
DB Location: local
MasterKey components: password only

What are the checks to bring up that error?

**Comment by Angelelz** [comment]
It says that when it doesn't have access to the Windows Password Vault, or can't save a new Credential into that Vault. I've actually never seen it before! It might be some restrictive setting, or a company set PC.

**Comment by BananaAcid** [comment]
This is actually on my private PC. Nothing special -worked a last week.
Does it do something with the user folder?

**Comment by Angelelz** [comment]
Hello, I'm sorry I've out for a couple weeks now, I've got a busier schedule now. Anyway, Have you figure this out? I can provide a different dll to check and possibly see the specific error we're dealing with

**Comment by BananaAcid** [comment]
I believe it is about me having encrypted the user folder - and causing problems with this.

**Comment by Angelelz** [comment]
Ok, could you change you DLL for  
[this one](https://github.com/Angelelz/WinHelloUnlock/files/4032104/WinHelloUnlock.zip)? The changes are in [TestBranch](https://github.com/Angelelz/WinHelloUnlock/tree/TestBranch) Branch. I eliminated the catching error part on that logic so we can see what's exactly going on.

**Comment by BananaAcid** [comment]
I tried this DLL for a few days and it works. Switching back, does not.

**Comment by Angelelz** [comment]
So you don't see any error message or error not handled? That's weird! I'll try to pin down the error, could you try [this one](https://github.com/Angelelz/WinHelloUnlock/files/4048822/WinHelloUnlock.zip) next?

**Comment by Angelelz** [comment]
Could you also try solution 3 in [this website](https://windowsreport.com/11939-credential-manager-no-working-windows-8/)? I actually don't know what could be causing you this issue, I'm kinda shooting in the dark here.

**Comment by BananaAcid** [comment]
I meant: it works as intended with your replacement, no errors- I’m kinda confused. Maybe a Windows update fixed it somehow.

**Comment by Angelelz** [comment]
So, is it fixed on both dll provided? And switching back to the regular version brings back the problem?

**Comment by BananaAcid** [comment]
getting the 11. Jan version, I got [this](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus)

But works. I did not try to fix the credentials manager (did not work for a while, now does) ... I'd say: fixed itself magically ...

**Comment by Angelelz** [comment]
What? did you get a virus alert? I don't understand.
Have you tried the official dll again?

**Comment by BananaAcid** [comment]
I realized, restating the PC, opening a  keepass file, it asks me again, if I want to use the plugin

Somehow, it is cursed for me

**Comment by Angelelz** [comment]
As soon as I get a bit more technical information I'll try to troubleshoot the bug.
What is the behaviour with each of the provided plugins?
