### ISSUE TITLE
WinHelloUnlock integration in GUI

### ISSUE THREAD

**Issue by Dschayem** [Angelelz/WinHelloUnlock#40]
Hello,

why is WinHelloUnlock integrated in the Options-Dialog of KeePass? It is not really conclusive, because it seems to be more practical in "File -> Database Settings", because in the dialog are no global options of WinHelloUnlock, but only database specific options.

Greetings

**Comment by Angelelz** [comment]
True, settings are database specific, but I feel WinHelloUnlock options should stay where they are, as they are also specific for the plugin and not just the database. Also, there could be general WinHelloUnlock setting that could be added in the future.
