### ISSUE TITLE
WinHelloUnlock always asking if you want to save biometic data

### ISSUE THREAD

**Issue by Dschayem** [Angelelz/WinHelloUnlock#41]
Hello,

WinHelloUnlock works as it should. But it always asks if i want to save credentials / biometric data for the main database, but i already saved data here.
You should know that i have one primary database - this one, i unlock with biometric data (WinHello). This database has no critical data in it; it is simply here to unlock 3 other databases via KeeAutoExec. i have enabled WinHelloUnlock for this main database and disabled for the other three. But from time to time WinHelloUnlock asks again and again if i want to activate it for this database, even if i already activated it. It works fine even if i click no, but it always asks if i want to save data. It seems somehow it happens when i open some other database, but i have no real clue when it happens.

Greetings

**Comment by Angelelz** [comment]
Try disabling the plugin for each database that does not uses it. Do it by having only one opened, while changing the setting. For all 3.
Let me know the result.

**Comment by Dschayem** [comment]
It seems to work now by doing these steps :-)

**Comment by Angelelz** [comment]
Perfect, when you open several databases at once, the plugin would show you a pop-up for each one! Just disable the plugin for each database and that will stop.
