### ISSUE TITLE
Error using WinHello with database saved in Google Drive locally synced folder

### ISSUE THREAD

**Issue by JohnLGalt** [Angelelz/WinHelloUnlock#42]
_**Describe the bug**_
This just started happening today.  I have been using WinHello with KeePass on a Windows 10 machine to use my WinX Hello PIN to log into my database, which has an extremely long and complicated Master PW only.  I just updated KeePass (portable) from 2.43 to 2.44 and WinHello is breaking on that same database.  If I export the database to another folder (not synchronized to Google Drive) WinHello works with KeePass 2.44 and that database with no issues.  If I revert to KP 2.43, it works perfectly fine with the database in my Google Drive synced folder.

_**To Reproduce**_
1. Open KP 2.44 (portable), open database in Google Drive folder
2. Enter WinX Hello PIN
3. See error (screenshot below)

_**Expected behavior**_
Obviously, I expect it to open my database as it always has.

_**Screenshot of error**_

![KeePass WinHello plugin error #1](https://user-images.githubusercontent.com/7432512/74184010-ff53e800-4c13-11ea-9966-1cfe95ee8bf2.png)

_**Additional context**_
I had a brainstorm to see if it would work from another folder, and v 2.44 + WinHello works as expected from another folder and an *exported* database, as well as a "save as" database to another location.  I also noticed that reverting to KP 2.43 works with the original database that is saved in my Google Drive locally synced folder.

**_List of all plugins in KP:_**

![KeePass WinHello plugin error #2](https://user-images.githubusercontent.com/7432512/74184628-1cd58180-4c15-11ea-9114-3808da2242d7.png)
![KeePass WinHello plugin error #3](https://user-images.githubusercontent.com/7432512/74184636-1fd07200-4c15-11ea-8bfb-74b9224f1fdb.png)
![KeePass WinHello plugin error #4](https://user-images.githubusercontent.com/7432512/74184642-22cb6280-4c15-11ea-8a7c-1fd6b56763f0.png)

Windows 10 Version 1909 (OS Build 18363.592)

**Comment by JohnLGalt** [comment]
I've since reverted to 2.43 (portable) to keep WinHello working as it should.  I'm not sure where exactly the idiosyncrasy lies, as it could be:

1. A Google Drive issue
2. A KP 2.44 specific version issue
3. An incompatibility b/w current WinHello and KP 2.44 only
4. Something stupid on my system itself
5. Something completely off the wall

I'm currently setting up a laptop on which I will test with *both* portable and installed version of KP 2.44 along with the same Google Drive locally synced file and see if the error manifests there as well or not.

**Comment by Angelelz** [comment]
I would say, before doing anything, head to options and delete WinHelloUnlock data for that particular database and create it again. Let me know if that helps.

**Comment by JohnLGalt** [comment]
Oh, Roger, didn't realize that option was there.  I will try our and see
what happens.

**Comment by JohnLGalt** [comment]
Question:  Could it have to do with the fact that I'm sharing the database through GDrive, and using on 2 physically different machines that both use hte same Microsoft account to login (and thus using  WinHello on both machines?

Both machines are WinX current 1909 builds, one a laptop and one a desktop....

**Comment by Angelelz** [comment]
It shouldn't! I actually share all my databases with gdrive and use WinHelloUnlock in two machines. WinHelloUnlock data is saved locally, and is different depending on the machine.

Let me know if deleting the data and saving it again helps

**Comment by JohnLGalt** [comment]
That seems to have fixed it this go around.  I have no idea why it was even doing it in the first place.

Odd.

Closing this as fixed.

**Comment by JohnLGalt** [comment]
Adding further comment - When I encountered the issue again (with the latest version) I was able to successfully delete the saved data and re-employ the hook and it is working perfectly again across both machines.

So, yes, deleting the saved data and saving it again works exactly as it should.
