### ISSUE TITLE
Incompatible with the latest Keepass version

### ISSUE THREAD

**Issue by joaochenriques** [Angelelz/WinHelloUnlock#43]
Hi,
Your plugin seems to be a great idea. However, the plugin is not compatible with the lastest version of Keepass. Can you upgrade please?
Regards,
JH

**Comment by Angelelz** [comment]
I have it working with the new KeePass version. If you are having problems try deleting the WinHelloUnlock data of the database in options, and then create it again.
Let me know if that helps

**Comment by joaochenriques** [comment]
Can you upload a compiled version for the current KeePass version?
Thanks in advance.

**Comment by Angelelz** [comment]
Updated. Remember to delete the database's WinHelloUnlock data to fix your issue. Please confirm to close this.

**Comment by joaochenriques** [comment]
It worked perfectly. Amazing job! Congratulations. Just one where is store the "database's WinHelloUnlock data"?

**Comment by Angelelz** [comment]
You can find the data in the credential manager. that's in control panel.
