### ISSUE TITLE
Undesired error message upon fingerprint unlock cancellation

### ISSUE THREAD

**Issue by zcahana** [Angelelz/WinHelloUnlock#48]
**Describe the bug**
When a fingerprint unlock attempt is canceled, there's an error message popping out (in its own dialog), accompanied by a bell sound: _"error decrypting the data: the request was canceled by the user"_

In my view this error message is undesired and annoying. The cancellation was initiated by myself (the user), hence the cancellation is not an error, but rather the desired behavior. I'd much prefer that after cancelling the fingerprint unlock, I'd return to the KeePass database unlock dialog (which anyway appears after I click the "OK" button in the error dialog).

**To Reproduce**
1. Open a KeePass database file and wait for the fingerprint unlock screen.
2. Cancel by either clicking the "Cancel" button, the "X" button at the top right, or just hit the "Esc" key.
3. Observe the error message pops up.

**Expected behavior**
After cancelling the fingerprint unlock, I'd return to the KeePass database unlock dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/17428696/93183805-1f1c3300-f744-11ea-954d-ed7d83fe6da8.png)

**Additional context**
KeePass v2.45
WinHelloUnlock 1.5

**Comment by Angelelz** [comment]
Hello there, thanks for taking the time to report.
I've been considering removing this behavior since it dates back from the times I was testing, but I wasn't sure. It'll be fixed in the next release.

**Comment by zcahana** [comment]
Thanks @Angelelz!
