### ISSUE TITLE
KeePass 2.xy portable support

### ISSUE THREAD

**Issue by MrDTeach** [Angelelz/WinHelloUnlock#49]
First of all, thanks for the great plugin!
WinHelloUnlock doesn't support KeePass 2.xy portable. can you fix it?

best regards

**Comment by selcukduman** [comment]
I use it with the portable version 2.46 without any problems.

**Comment by MrDTeach** [comment]
If I use the Plugin with KeePass 2.46, I get an Error:
![image](https://user-images.githubusercontent.com/7045474/95827921-a1dce180-0d34-11eb-92f2-c0e91d3ad215.png)

**Comment by Angelelz** [comment]
Hello there, thanks for reporting the issue.
I've been trying to reproduce the issue without success, I've successfully used the plugin with both the installed version and the portable version of KeePass.
Have you tried with the installer version?

**Comment by Angelelz** [comment]
I would suggest to take a look at your config file, since [it had been linked](https://github.com/Angelelz/WinHelloUnlock/issues/47) to false positive incompatible behaviors.

**Comment by MrDTeach** [comment]
Hello,

It works perfect with the installed version.
There is the config. I had to rename it for the upload as a .jpeg.

![KeePass exe config](https://user-images.githubusercontent.com/7045474/96361465-28733380-1126-11eb-9429-8c6538a411cb.jpeg)

**Comment by MrDTeach** [comment]
Hello,

yes, it works with the installed version.
Here is the downloadlink for the config.
https://cloud.kroell.click/index.php/s/9YREtktdTRDLPE7

**Comment by Angelelz** [comment]
Then I would suggest creating a portable instalación from your installed version. This can be achieved using the instructions found on the [KeePass configuration help page](https://keepass.info/help/base/configuration.html):
`If you are currently using a locally installed version of KeePass (installed by the KeePass installer) and want to create a portable version of it, first copy all files of KeePass to the portable device. Then get the configuration file from your user directory (application data, see above) and copy it over the configuration file on the portable device.`

**Comment by MrDTeach** [comment]
I can create a portable Version with the installed version. But if I run it, the plugin don't do anything. I did not get the promp withe the question to aktivate win helle for this Keepass-Database and if I reopen Keepass and the database I have to fill the Password.

**Comment by Angelelz** [comment]
I just Updated the plugin and the Keepass base version. Please let me know if that fixed the issue.

**Comment by MrDTeach** [comment]
Thanks. 
Now I have the problem with the "incompatible" Error again. 

I tried to fix it with a now download of the portable version. It doesn't work.
Then I made a portable Version from a installed Version. It dosen't work, too.
Where can I get a newer Version of the: "KeePass.exe.config"?

Best regards

**Comment by MrDTeach** [comment]
![image](https://user-images.githubusercontent.com/7045474/99639896-85754880-2a48-11eb-8a26-a79969178b4c.png)

**Comment by MrDTeach** [comment]
It works with the last KeePass Update.
Thanks for help! 

best regards
