### ISSUE TITLE
Creating WinHelloUnlock data for a database leads to error

### ISSUE THREAD

**Issue by Peitscha** [Angelelz/WinHelloUnlock#55]
Hey!

Even though the Windows Hello unlock for my user profile on my laptop itself (not KeePass) is working flawlessly, it does not for the KeePass plugin WinHelloUnlock. The only message it says is "Something went wrong. Please try again." (as shown in yellow in German).

![grafik](https://user-images.githubusercontent.com/38219901/109723662-b1a77600-7bae-11eb-8b21-ed581ec97514.png)

The other plugin KeePassWinHello has about the same problem after the successful setup although I just need to try it a second time to unlock the database (instead of not working at all with WinHelloUnlock).

I have a ZenBook UX433FN with Windows 10 Pro on version 19042.

Is there a way to fix this issue?

Thank you in advance,
Gabriel

**Comment by xperiandri** [comment]
I had the same issue.
I don't remember what I did but now I always have 
![image](https://user-images.githubusercontent.com/2365592/113511979-2fbeba00-956b-11eb-8b78-fc95da7ac08b.png)

**Comment by xperiandri** [comment]
Deleting keys and creating new (by pressing OK several time event though the same as @Peitscha error appeared) helped
![image](https://user-images.githubusercontent.com/2365592/113512157-0b171200-956c-11eb-8a57-bbf16fe2ea87.png)
