### ISSUE TITLE
autotype option?

### ISSUE THREAD

**Issue by toozdey** [Angelelz/WinHelloUnlock#56]
Thanks for the useful addon. Would it be possible for a new feature to trigger autotype when scanning fingerprint? I've been searching for a while on how to autotype with fingerprint but haven't found a solution.

**Comment by Angelelz** [comment]
There is an autotype option already in Keepass itself.  There is a global Autotype hotkey option, if you hit it, and Keepass is locked, it will automatically try to unlock it with this plugin.
