### ISSUE TITLE
Build instructions not in README, fresh clone fails with "type or namespace name 'KeePass' could not be found"

### ISSUE THREAD

**Issue by Charlweed** [Angelelz/WinHelloUnlock#57]
**Describe the bug**
The repository is not buildable when the repository is first cloned, Visual Studio fails with many errors:
Error	CS0246	The type or namespace name 'KeePass' could not be found (are you missing a using directive or an assembly reference?)	KeePassWinHello	L:\projects\3rd_party\KeePassWinHello\src\KeePassWinHelloExt.cs	6	Active

If this project requires additional dependencies and configuration, it would be great if they were documented in the README so users can build successfully. 
**To Reproduce**
1. Clone repository in Visual Studio
2. Select "Build Solution" from Visual Studio "Build" menu
3. See error

**Additional context**
This is a newly installed instance of Visual Studio 2019, and a fresh clone of the WinHelloUnlock repository.

**Comment by Angelelz** [comment]
Thanks for submitting the issue. Will be fixed soon.
