### ISSUE TITLE
Ask for two Hello authentications 

### ISSUE THREAD

**Issue by apelec** [Angelelz/WinHelloUnlock#58]
I am not sure this is a bug, just an oversight perhaps. I have plugin KeeAutoExec installed to automatically open a second database. I recently installed KeePassUnlock and it correctly opens Keepass but it seems to want a second authentication for the second database which is already open by KeeAutoExec.  A cancel allows to proceed.

It would be nice not to have to cancel.

 **To Reproduce**
have two keepass db
Install KeeAutoExec
configure it to open the 2nd dB in a new tab
Install KeePassWinUnlock

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0
 - KeePass Version 2.47
 - Plugin Version  1.6
 - Hardware info Desktop i7, 16GB
 
 **KeePass settings and environment**
 - Is secure desktop enabled
 - Is KeePass running under Administrator: yes
 - Installed plugins (if any)  AutoTypeSplitter V1.2  KeyAutoExec V2.4

**Comment by Angelelz** [comment]
It will be fixed in next version.

**Comment by Angelelz** [comment]
Also, depending on your particular setup you would probably need to disable the plugin for the 2nd database in options.
