### ISSUE TITLE
Hi - This is not an issue, but requesting if you can add a future.

### ISSUE THREAD

**Issue by devopsgit9** [Angelelz/WinHelloUnlock#66]
Hi,
Thank you for adding bio-metric login.
The bio metric prompts only first time when we open the application.
But is it possible to add a future where the bio-metric prompts each time when even opening an entry with in the application, which will be more secured.

**Comment by thomasbonr** [comment]
You just have to go into the option menu and you can change the parameters when the database is locked.

**Comment by Angelelz** [comment]
Just add the auto locking feature on Keepass.
