### ISSUE TITLE
Master Key is Invalid Error

### ISSUE THREAD

**Issue by macoirc** [Angelelz/WinHelloUnlock#77]
**Describe the bug**
KeePass is displaying an error message that the master key is invalid, before prompting me to authenticate through Windows Hello. After clicking 'OK' it progresses normally and the database opens fine. Just a nuisance more than anything, but figured I'd report it because this plugin is a life saver!

**To Reproduce**
1. Open a WHU protected database, or unlock an already open db.
2. An error message immediately pops up stating there was a key error, before authentication happens.
3. Click OK and everything progresses as expected.

**Expected behavior**
Authentication through WH should happen first, so that the master key can be retrieved from the Windows credential store.

**Screenshots**
<img width="287" alt="image" src="https://github.com/Angelelz/WinHelloUnlock/assets/5374176/9ebd0977-bebc-495c-8192-e2f1782d24ac">

**Additional context**
KeePass 2.55
WHU 1.6.1

**Comment by macoirc** [comment]
I wondered if it was OneDrive messing things up so I copied the database to my C:\temp to test and the same thing happened...Error, hit OK, scan fingerprint, database opens fine.

**Comment by tcp3389ru** [comment]
Hello. Disable "enter master key on secure desktop"

**Comment by macoirc** [comment]
> Hello. Disable "enter master key on secure desktop"

Perfect, that did it! Thank you so much.
