### ISSUE TITLE
Missing correct version number on WinHelloUnlock.dll

### ISSUE THREAD

**Issue by Erroneuz** [Angelelz/WinHelloUnlock#9]
Version v0.99.2 doesn't contain 0.99.2 on the DLL, but contains 0.99.0 as version number, which means KeePass believes there is a newer version, even if using the DLL from 0.99.2 release.

![Image of update check](https://i.imgur.com/N7RTbM9.png)

Thanks for a great addon.

**Comment by Angelelz** [comment]
Sorry for the inconvenience, I edited the release and replaced the DLL. You can download again.
